import { readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";

/** Every .ts source that must be loadable: src/** and scripts/**, excluding tests and this generator's own output. */
export function loadableFiles(root: string): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name);
      if (statSync(p).isDirectory()) { walk(p); continue; }
      // FACTORY-569: every downstream use of this string (loadTestPathFor's
      // "/" split, the generated file's own import specifier) is POSIX-shaped
      // on purpose — an ES module specifier is always "/"-separated, even on
      // win32. `relative` returns the OS-native separator (backslash on
      // win32), so it must be normalized here, once, rather than at each
      // of those callers.
      if (name.endsWith(".ts") && !name.endsWith(".d.ts")) out.push(relative(root, p).split(sep).join("/"));
    }
  };
  for (const top of ["src", "scripts"]) walk(join(root, top));
  return out.sort();
}

/** test/load/<path with / → __>.load.test.ts */
export const loadTestPathFor = (file: string) => `test/load/${file.replace(/\.ts$/, "").replace(/\//g, "__")}.load.test.ts`;

/** Entry-point scripts run on import (they call process.exit / hit the network); they are load-tested as a subprocess with a guard env instead. */
export const RUNS_ON_IMPORT = new Set([
  "scripts/load/generate.ts", "scripts/release/check.ts", "scripts/release/release.ts",
  "scripts/coverage/gate.ts", "scripts/verify-generated-is-committed.ts",
  "scripts/verify-spawn-effort.ts", "scripts/verify-workspace-ground-truth.ts", "scripts/verify-review-commit-immutability.ts", "src/daemon/index.ts",
  // FACTORY-892: calls main() unconditionally at import time — real herdr
  // I/O (workspace.create, agent.start, pane.processInfo, pane.close,
  // workspace.close). Importing it during `bun test` must not do any of
  // that; it is run for real only by the dedicated `spawn-smoke` CI job.
  "scripts/verify-ci-spawn-smoke.ts",
  // BUTCHR-250: a one-off vendoring script that fetches a live URL and
  // writes src/tools/html4-named-entities.generated.ts as a side effect of
  // being run — importing it must not actually hit the network or rewrite
  // a committed generated file as a side effect of a "does this load" check.
  "scripts/vendor/html4-entities.ts",
  // BUTCHR-245: calls main() unconditionally at import time — real herdr I/O
  // (workspace.list/pane.list/agent.list, and workspace.close under
  // --execute). Importing it during `bun test` must not do any of that.
  "scripts/reap-dry-run.ts",
  // BUTCHR-54: a real build step (spawns `git`, invokes `Bun.build`, writes
  // `dist/`) — importing it must not actually run all that as a side effect
  // of a "does this load" check.
  "scripts/build/build.ts",
  // BUTCHR-268: calls main() unconditionally at import time — real herdr I/O
  // (agent.list, workspace.list/create/close, agent.start, pane.close), and
  // with no `argv[2]` under `bun test` its default mode runs the full `gaps`
  // sweep. Importing it during `bun test` must not do any of that.
  "scripts/repro-pane-busy.ts",
]);

export function loadTestSource(file: string): string {
  const rel = JSON.stringify("../../" + file);
  const importPath = JSON.stringify("../../" + file.replace(/\.ts$/, ".js"));
  const name = JSON.stringify("loads: " + file);
  if (RUNS_ON_IMPORT.has(file)) {
    // Entry point: importing would RUN it. A transpile proves syntax; resolving
    // each relative import proves the file is wired to things that exist.
    return [
      `// GENERATED by scripts/load — do not edit. Proves ${file} parses and its imports resolve.`,
      'import { test, expect } from "bun:test";',
      `test(${name}, async () => {`,
      `  const here = new URL(${rel}, import.meta.url);`,
      '  const src = await Bun.file(here).text();',
      '  const t = new Bun.Transpiler({ loader: "ts" });',
      '  expect(() => t.transformSync(src)).not.toThrow();',
      '  for (const imp of t.scanImports(src)) {',
      '    if (!imp.path.startsWith(".")) continue;',
      '    const target = new URL(imp.path.replace(/[.]js$/, ".ts"), here);',
      '    expect(await Bun.file(target).exists(), "unresolved import " + imp.path).toBe(true);',
      '  }',
      '});',
      '',
    ].join("\n");
  }
  return [
    `// GENERATED by scripts/load — do not edit. Proves ${file} is loadable.`,
    'import { test, expect } from "bun:test";',
    `test(${name}, async () => {`,
    `  const mod = await import(${importPath});`,
    '  expect(mod).toBeDefined();',
    '});',
    '',
  ].join("\n");
}
