[test]
preload = ["./test/setup/isolated-workspaces.ts"]
coverage = true
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coveragePathIgnorePatterns = ["test/**"]
