// GENERATED by scripts/load — do not edit. Proves scripts/real-guard-server.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/real-guard-server.ts", async () => {
  const mod = await import("../../scripts/real-guard-server.js");
  expect(mod).toBeDefined();
});
