// GENERATED by scripts/load — do not edit. Proves scripts/wsl-host/wsl-conf.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/wsl-host/wsl-conf.ts", async () => {
  const mod = await import("../../scripts/wsl-host/wsl-conf.js");
  expect(mod).toBeDefined();
});
