// GENERATED by scripts/load — do not edit. Proves scripts/deploy/rollback-decision.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/deploy/rollback-decision.ts", async () => {
  const mod = await import("../../scripts/deploy/rollback-decision.js");
  expect(mod).toBeDefined();
});
