// GENERATED by scripts/load — do not edit. Proves scripts/preflight.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/preflight.ts", async () => {
  const mod = await import("../../scripts/preflight.js");
  expect(mod).toBeDefined();
});
