// GENERATED by scripts/load — do not edit. Proves scripts/verify-rules-page-browser.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/verify-rules-page-browser.ts", async () => {
  const mod = await import("../../scripts/verify-rules-page-browser.js");
  expect(mod).toBeDefined();
});
