// GENERATED by scripts/load — do not edit. Proves scripts/build/web-notices.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/build/web-notices.ts", async () => {
  const mod = await import("../../scripts/build/web-notices.js");
  expect(mod).toBeDefined();
});
