// GENERATED by scripts/load — do not edit. Proves scripts/verify-channel-delivery.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/verify-channel-delivery.ts", async () => {
  const mod = await import("../../scripts/verify-channel-delivery.js");
  expect(mod).toBeDefined();
});
