// GENERATED by scripts/load — do not edit. Proves scripts/windows-host/health.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/windows-host/health.ts", async () => {
  const mod = await import("../../scripts/windows-host/health.js");
  expect(mod).toBeDefined();
});
