// GENERATED by scripts/load — do not edit. Proves scripts/deploy/watchdog.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/deploy/watchdog.ts", async () => {
  const mod = await import("../../scripts/deploy/watchdog.js");
  expect(mod).toBeDefined();
});
