// GENERATED by scripts/load — do not edit. Proves scripts/repro-pane-busy.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/repro-pane-busy.ts", async () => {
  const mod = await import("../../scripts/repro-pane-busy.js");
  expect(mod).toBeDefined();
});
