// GENERATED by scripts/load — do not edit. Proves scripts/migrate-workspace-layout.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/migrate-workspace-layout.ts", async () => {
  const mod = await import("../../scripts/migrate-workspace-layout.js");
  expect(mod).toBeDefined();
});
