// GENERATED by scripts/load — do not edit. Proves scripts/wsl-host/cli.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/wsl-host/cli.ts", async () => {
  const mod = await import("../../scripts/wsl-host/cli.js");
  expect(mod).toBeDefined();
});
