// GENERATED by scripts/load — do not edit. Proves scripts/audit-alias-calls.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/audit-alias-calls.ts", async () => {
  const mod = await import("../../scripts/audit-alias-calls.js");
  expect(mod).toBeDefined();
});
