// GENERATED by scripts/load — do not edit. Proves src/daemon/filesystem-loop.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/daemon/filesystem-loop.ts", async () => {
  const mod = await import("../../src/daemon/filesystem-loop.js");
  expect(mod).toBeDefined();
});
