// GENERATED by scripts/load — do not edit. Proves src/rules/agent-harness.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/rules/agent-harness.ts", async () => {
  const mod = await import("../../src/rules/agent-harness.js");
  expect(mod).toBeDefined();
});
