// GENERATED by scripts/load — do not edit. Proves src/labels/sweep.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/labels/sweep.ts", async () => {
  const mod = await import("../../src/labels/sweep.js");
  expect(mod).toBeDefined();
});
