// GENERATED by scripts/load — do not edit. Proves src/agents/account-lifecycle.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/account-lifecycle.ts", async () => {
  const mod = await import("../../src/agents/account-lifecycle.js");
  expect(mod).toBeDefined();
});
