// GENERATED by scripts/load — do not edit. Proves src/agents/codex-dialog-sightings.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/codex-dialog-sightings.ts", async () => {
  const mod = await import("../../src/agents/codex-dialog-sightings.js");
  expect(mod).toBeDefined();
});
