// GENERATED by scripts/load — do not edit. Proves src/tools/journald-prefix.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/tools/journald-prefix.ts", async () => {
  const mod = await import("../../src/tools/journald-prefix.js");
  expect(mod).toBeDefined();
});
