// GENERATED by scripts/load — do not edit. Proves src/web/write-rate-limit.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/web/write-rate-limit.ts", async () => {
  const mod = await import("../../src/web/write-rate-limit.js");
  expect(mod).toBeDefined();
});
