// GENERATED by scripts/load — do not edit. Proves src/media/registry.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/media/registry.ts", async () => {
  const mod = await import("../../src/media/registry.js");
  expect(mod).toBeDefined();
});
