// GENERATED by scripts/load — do not edit. Proves src/tools/docs.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/tools/docs.ts", async () => {
  const mod = await import("../../src/tools/docs.js");
  expect(mod).toBeDefined();
});
