// GENERATED by scripts/load — do not edit. Proves src/setup/jira-identity-file.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/setup/jira-identity-file.ts", async () => {
  const mod = await import("../../src/setup/jira-identity-file.js");
  expect(mod).toBeDefined();
});
