// GENERATED by scripts/load — do not edit. Proves src/jira-watch/routes.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/jira-watch/routes.ts", async () => {
  const mod = await import("../../src/jira-watch/routes.js");
  expect(mod).toBeDefined();
});
