// GENERATED by scripts/load — do not edit. Proves src/agents/managed-session-escalation-watcher.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/managed-session-escalation-watcher.ts", async () => {
  const mod = await import("../../src/agents/managed-session-escalation-watcher.js");
  expect(mod).toBeDefined();
});
