// GENERATED by scripts/load — do not edit. Proves src/agents/check-in-exit.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/check-in-exit.ts", async () => {
  const mod = await import("../../src/agents/check-in-exit.js");
  expect(mod).toBeDefined();
});
