// GENERATED by scripts/load — do not edit. Proves src/resources/power-scale.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/resources/power-scale.ts", async () => {
  const mod = await import("../../src/resources/power-scale.js");
  expect(mod).toBeDefined();
});
