// GENERATED by scripts/load — do not edit. Proves src/web/daemon-logs.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/web/daemon-logs.ts", async () => {
  const mod = await import("../../src/web/daemon-logs.js");
  expect(mod).toBeDefined();
});
