// GENERATED by scripts/load — do not edit. Proves src/atlassian/client.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/atlassian/client.ts", async () => {
  const mod = await import("../../src/atlassian/client.js");
  expect(mod).toBeDefined();
});
