// GENERATED by scripts/load — do not edit. Proves src/resources/write-json-file.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/resources/write-json-file.ts", async () => {
  const mod = await import("../../src/resources/write-json-file.js");
  expect(mod).toBeDefined();
});
