// GENERATED by scripts/load — do not edit. Proves src/rules/write-rules.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/rules/write-rules.ts", async () => {
  const mod = await import("../../src/rules/write-rules.js");
  expect(mod).toBeDefined();
});
