// GENERATED by scripts/load — do not edit. Proves src/agents/residency-census.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/residency-census.ts", async () => {
  const mod = await import("../../src/agents/residency-census.js");
  expect(mod).toBeDefined();
});
