// GENERATED by scripts/load — do not edit. Proves src/config/effective-env.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/config/effective-env.ts", async () => {
  const mod = await import("../../src/config/effective-env.js");
  expect(mod).toBeDefined();
});
