// GENERATED by scripts/load — do not edit. Proves src/agents/restored-pane-escalation.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/restored-pane-escalation.ts", async () => {
  const mod = await import("../../src/agents/restored-pane-escalation.js");
  expect(mod).toBeDefined();
});
