// GENERATED by scripts/load — do not edit. Proves src/notify/codex-channel-relay.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/notify/codex-channel-relay.ts", async () => {
  const mod = await import("../../src/notify/codex-channel-relay.js");
  expect(mod).toBeDefined();
});
