// GENERATED by scripts/load — do not edit. Proves src/resources/session-definition-manage.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/resources/session-definition-manage.ts", async () => {
  const mod = await import("../../src/resources/session-definition-manage.js");
  expect(mod).toBeDefined();
});
