// GENERATED by scripts/load — do not edit. Proves src/agents/config-inventory-links.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/config-inventory-links.ts", async () => {
  const mod = await import("../../src/agents/config-inventory-links.js");
  expect(mod).toBeDefined();
});
