// GENERATED by scripts/load — do not edit. Proves src/tools/jira-project-scope.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/tools/jira-project-scope.ts", async () => {
  const mod = await import("../../src/tools/jira-project-scope.js");
  expect(mod).toBeDefined();
});
