// GENERATED by scripts/load — do not edit. Proves src/web/jira-connection-test.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/web/jira-connection-test.ts", async () => {
  const mod = await import("../../src/web/jira-connection-test.js");
  expect(mod).toBeDefined();
});
