// GENERATED by scripts/load — do not edit. Proves src/agents/session-limit-watch.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/session-limit-watch.ts", async () => {
  const mod = await import("../../src/agents/session-limit-watch.js");
  expect(mod).toBeDefined();
});
