// GENERATED by scripts/load — do not edit. Proves src/daemon/currency.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/daemon/currency.ts", async () => {
  const mod = await import("../../src/daemon/currency.js");
  expect(mod).toBeDefined();
});
