// GENERATED by scripts/load — do not edit. Proves src/rules/status-clause-warning.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/rules/status-clause-warning.ts", async () => {
  const mod = await import("../../src/rules/status-clause-warning.js");
  expect(mod).toBeDefined();
});
