// GENERATED by scripts/load — do not edit. Proves src/rules/display-label.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/rules/display-label.ts", async () => {
  const mod = await import("../../src/rules/display-label.js");
  expect(mod).toBeDefined();
});
