// GENERATED by scripts/load — do not edit. Proves src/web/settings-unit-hint.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/web/settings-unit-hint.ts", async () => {
  const mod = await import("../../src/web/settings-unit-hint.js");
  expect(mod).toBeDefined();
});
