// GENERATED by scripts/load — do not edit. Proves src/settings/write-settings.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/settings/write-settings.ts", async () => {
  const mod = await import("../../src/settings/write-settings.js");
  expect(mod).toBeDefined();
});
