// GENERATED by scripts/load — do not edit. Proves src/media/blind-spot.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/media/blind-spot.ts", async () => {
  const mod = await import("../../src/media/blind-spot.js");
  expect(mod).toBeDefined();
});
