// GENERATED by scripts/load — do not edit. Proves src/tools/alias-audit.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/tools/alias-audit.ts", async () => {
  const mod = await import("../../src/tools/alias-audit.js");
  expect(mod).toBeDefined();
});
