// GENERATED by scripts/load — do not edit. Proves src/terminal/pty-attach.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/terminal/pty-attach.ts", async () => {
  const mod = await import("../../src/terminal/pty-attach.js");
  expect(mod).toBeDefined();
});
