// GENERATED by scripts/load — do not edit. Proves src/setup/setup-code.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/setup/setup-code.ts", async () => {
  const mod = await import("../../src/setup/setup-code.js");
  expect(mod).toBeDefined();
});
