// GENERATED by scripts/load — do not edit. Proves src/resources/provider-adapter.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/resources/provider-adapter.ts", async () => {
  const mod = await import("../../src/resources/provider-adapter.js");
  expect(mod).toBeDefined();
});
