// GENERATED by scripts/load — do not edit. Proves src/agents/stand-down.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/stand-down.ts", async () => {
  const mod = await import("../../src/agents/stand-down.js");
  expect(mod).toBeDefined();
});
