// GENERATED by scripts/load — do not edit. Proves src/tools/session-freeze-tools.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/tools/session-freeze-tools.ts", async () => {
  const mod = await import("../../src/tools/session-freeze-tools.js");
  expect(mod).toBeDefined();
});
