// GENERATED by scripts/load — do not edit. Proves src/cli/session-cli.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/cli/session-cli.ts", async () => {
  const mod = await import("../../src/cli/session-cli.js");
  expect(mod).toBeDefined();
});
