// GENERATED by scripts/load — do not edit. Proves src/rules/capacity-role-migration.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/rules/capacity-role-migration.ts", async () => {
  const mod = await import("../../src/rules/capacity-role-migration.js");
  expect(mod).toBeDefined();
});
