// GENERATED by scripts/load — do not edit. Proves src/resources/link-reconcile.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/resources/link-reconcile.ts", async () => {
  const mod = await import("../../src/resources/link-reconcile.js");
  expect(mod).toBeDefined();
});
