// GENERATED by scripts/load — do not edit. Proves src/resources/linked-discovery.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/resources/linked-discovery.ts", async () => {
  const mod = await import("../../src/resources/linked-discovery.js");
  expect(mod).toBeDefined();
});
