// GENERATED by scripts/load — do not edit. Proves src/labels/label-scan.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/labels/label-scan.ts", async () => {
  const mod = await import("../../src/labels/label-scan.js");
  expect(mod).toBeDefined();
});
