// GENERATED by scripts/load — do not edit. Proves src/resources/confluence-page-query.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/resources/confluence-page-query.ts", async () => {
  const mod = await import("../../src/resources/confluence-page-query.js");
  expect(mod).toBeDefined();
});
