// GENERATED by scripts/load — do not edit. Proves src/tools/html4-named-entities.generated.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/tools/html4-named-entities.generated.ts", async () => {
  const mod = await import("../../src/tools/html4-named-entities.generated.js");
  expect(mod).toBeDefined();
});
