// GENERATED by scripts/load — do not edit. Proves src/workspace/registry.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/workspace/registry.ts", async () => {
  const mod = await import("../../src/workspace/registry.js");
  expect(mod).toBeDefined();
});
