// GENERATED by scripts/load — do not edit. Proves src/catamorbius/mapping.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/catamorbius/mapping.ts", async () => {
  const mod = await import("../../src/catamorbius/mapping.js");
  expect(mod).toBeDefined();
});
