// GENERATED by scripts/load — do not edit. Proves src/notify/deliver.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/notify/deliver.ts", async () => {
  const mod = await import("../../src/notify/deliver.js");
  expect(mod).toBeDefined();
});
