// GENERATED by scripts/load — do not edit. Proves src/rules/rule-form-catalog.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/rules/rule-form-catalog.ts", async () => {
  const mod = await import("../../src/rules/rule-form-catalog.js");
  expect(mod).toBeDefined();
});
