// GENERATED by scripts/load — do not edit. Proves src/web/origin-guard-log.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/web/origin-guard-log.ts", async () => {
  const mod = await import("../../src/web/origin-guard-log.js");
  expect(mod).toBeDefined();
});
