// GENERATED by scripts/load — do not edit. Proves src/resources/url-to-resource.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/resources/url-to-resource.ts", async () => {
  const mod = await import("../../src/resources/url-to-resource.js");
  expect(mod).toBeDefined();
});
