// GENERATED by scripts/load — do not edit. Proves src/accounts/identity.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/accounts/identity.ts", async () => {
  const mod = await import("../../src/accounts/identity.js");
  expect(mod).toBeDefined();
});
