// GENERATED by scripts/load — do not edit. Proves src/daemon/health.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/daemon/health.ts", async () => {
  const mod = await import("../../src/daemon/health.js");
  expect(mod).toBeDefined();
});
