// GENERATED by scripts/load — do not edit. Proves src/agents/idle-dialog.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/agents/idle-dialog.ts", async () => {
  const mod = await import("../../src/agents/idle-dialog.js");
  expect(mod).toBeDefined();
});
