// GENERATED by scripts/load — do not edit. Proves src/resources/jira-project.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/resources/jira-project.ts", async () => {
  const mod = await import("../../src/resources/jira-project.js");
  expect(mod).toBeDefined();
});
