// GENERATED by scripts/load — do not edit. Proves src/mcp/registration.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/mcp/registration.ts", async () => {
  const mod = await import("../../src/mcp/registration.js");
  expect(mod).toBeDefined();
});
