// GENERATED by scripts/load — do not edit. Proves src/settings/settings-file.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/settings/settings-file.ts", async () => {
  const mod = await import("../../src/settings/settings-file.js");
  expect(mod).toBeDefined();
});
