// GENERATED by scripts/load — do not edit. Proves src/web/csrf.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/web/csrf.ts", async () => {
  const mod = await import("../../src/web/csrf.js");
  expect(mod).toBeDefined();
});
